# Generated by Django 4.2.16 on 2024-10-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_rating_cat_alter_rating_rate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_once',
        ),
        migrations.AlterField(
            model_name='rating',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='cats.cat'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'cat'), name='unique_rate'),
        ),
    ]
